import { HorizontalSpacer } from "spacers.slint";
export component FileCard inherits TouchArea {
    in property <string> name: "name.type";
    in property <string> size: "6.5MB";
    in property <string> path: "";

    mouse-cursor: pointer;

    Rectangle {
        background: parent.has-hover ? rgba(225, 235, 242, 1) : rgba(256, 256, 256, 1);
        border-radius: 12px;
        animate background {
            duration: 150ms;
            easing: ease-out;
        }

        HorizontalLayout {
            padding: 12px;
            spacing: 32px;

            HorizontalLayout {
                alignment: start;
                vertical-stretch: 0;
                horizontal-stretch: 0;
                Rectangle {
                    height: 32px;
                    width: 32px;
                    background: white;
                    border-width: 2px;
                    border-color: black;
                }
            }

            Text {
                text: name;
                font-size: 24px;
                font-weight: 600;
                horizontal-alignment: left;
                vertical-alignment: center;

                color: black;
            }

            HorizontalSpacer { }

            Text {
                text: size;
                font-size: 24px;
                horizontal-alignment: left;
                vertical-alignment: center;

                color: rgba(0,0,0,0.5);
            }
        }
    }
}
