import {
    Button,
    LineEdit,
    HorizontalBox,
    VerticalBox,
} from "std-widgets.slint";
import { MyButton } from "my_button.slint";
import { LoginScreen } from "login_screen.slint";
import { MainPage } from "main_page.slint";
import { FileExplorer, File, DirEntry } from "file_explorer.slint";


export component MainWindow inherits Window {
    title: "Personal Cloud";

    min-width: 1000px;
    min-height: 800px;

    preferred-width: 1400px;
    preferred-height: 800px;

    callback try-login(string, string);

    callback get(string);
    callback post();
    callback logout();
    callback delete(string);
    callback create-dir(string);

    in-out property <bool> is-logged: false;

    in property <[File]> files: [];
    in property <[DirEntry]> subdirs: [];
    in property <string> current-path: "/";

    callback navigate-to-dir(string);
    callback navigate-back();

    background: white;

    if !is-logged: LoginScreen {
        try-login(name, passwd) => {
            root.try-login(name, passwd);
        }
    }

    if is-logged: MainPage {
        files: root.files;
        subdirs: subdirs;
        current-path: current-path;

        navigate-back => {
            navigate-back();
        }

        navigate-to-dir(path) => {
            navigate-to-dir(path);
        }

        get(file-path) => {
            root.get(file-path);
        }
        post() => {
            root.post();
        }
        logout => {
            root.logout();
        }
        delete(path) => {
            delete(path);
        }

        create-dir(name) => {
            create-dir(name);
        }
    }
}
