import { MyButton } from "my_button.slint";
import {
    Button,
    LineEdit,
    HorizontalBox,
    VerticalBox,
} from "std-widgets.slint";
import { FileExplorer, File, DirEntry } from "file_explorer.slint";
import { FileMetadataSection } from "file_metadata_section.slint";
import { MyButton } from "my_button.slint";
import { ActionPanel } from "action_panel.slint";
import { HorizontalSpacer } from "spacers.slint";

export component MainPage inherits Rectangle {
    callback get(string);
    callback delete(string);
    callback post();
    callback logout();
    callback create-dir(string);

    callback update-metadata(int);

    in property <[File]> files: [];
    in property <[DirEntry]> subdirs: [];
    in property <string> current-path: "/";

    property <string> folder-name;

    callback navigate-to-dir(string);
    callback navigate-back();

    property <bool> creating-dir: false;

    background: rgba(195, 213, 235, 1);

    VerticalLayout {
        padding: 8px;
        spacing: 16px;

        HorizontalLayout {
            vertical-stretch: 1;
            spacing: 16px;
            padding: 16px;

            FileExplorer {
                vertical-stretch: 1;
                drop-shadow-blur: 30px;
                drop-shadow-color: rgba(0, 0, 0, 0.35);

                files: files;
                subdirs: subdirs;
                current-path: current-path;

                navigate-to-dir(path) => {
                    metadata-section.file-name = "-";
                    metadata-section.path = "-";
                    metadata-section.size = "-";
                    navigate-to-dir(path);
                }

                navigate-back => {
                    navigate-back();
                }

                update-metadata(name, path, size) => {
                    metadata-section.file-name = name;
                    metadata-section.path = path;
                    metadata-section.size = size;
                }
            }

            metadata-section := FileMetadataSection {
                vertical-stretch: 1;
                drop-shadow-blur: 30px;
                drop-shadow-color: rgba(0, 0, 0, 0.35);

                get(path) => {
                    get(path);
                }

                delete(path) => {
                    delete(path);
                    self.file-name = "-";
                    self.path = "-";
                    self.size = "-";
                }
            }
        }

        HorizontalLayout {
            min-height: 80px;

            HorizontalSpacer {
                horizontal-stretch: 1;
            }

            ActionPanel {
                horizontal-stretch: 0.1;
                drop-shadow-blur: 30px;
                drop-shadow-color: rgba(0, 0, 0, 0.35);

                post => {
                    post();
                }

                create-dir => {
                    creating-dir = true;
                }

                logout => {
                    logout();
                }
            }

            HorizontalSpacer {
                horizontal-stretch: 1;
            }
        }
    }

    if(creating-dir): Rectangle {
        background: rgba(0,0,0, 0.5);
        height: 100%;
        width: 100%;

        VerticalLayout {
            alignment: center;

            property <string> username;
            property <string> passwd;
            callback try-login(string, string);

            HorizontalLayout {
                alignment: center;

                Rectangle {
                    width: 350px;
                    background: rgba(22, 32, 64, 0.8);
                    border-radius: 32px;

                    VerticalBox {
                        spacing: 15px;
                        padding: 18px;

                        VerticalLayout {
                            spacing: 5px;
                            Text {
                                text: "Folder";
                                font-size: 16px;
                                color: white;
                            }

                            LineEdit {
                                placeholder-text: "Enter Folder Name";
                                font-size: 16px;
                                text <=> folder-name;
                            }
                        }

                        HorizontalLayout {
                            spacing: 16px;

                            MyButton {
                                text: "Cancel";

                                static-bg: rgba(232, 116, 116, 0.25);
                                hover-bg: rgba(232, 116, 116, 0.5);

                                font-color: white;

                                clicked => {
                                    creating-dir = false;
                                }
                            }

                            MyButton {
                                text: "Submit";

                                static-bg: rgba(154, 252, 187, 0.25);
                                hover-bg: rgba(154, 252, 187, 0.5);

                                font-color: white;

                                clicked => {
                                    creating-dir = false;
                                    create-dir(folder-name);
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}
