import { MyButton } from "my_button.slint";
import {
    Button,
    LineEdit,
    HorizontalBox,
    VerticalBox,
} from "std-widgets.slint";
import { FileExplorer, File, DirEntry } from "file_explorer.slint";
import { FileMetadataSection } from "file_metadata_section.slint";
import { MyButton } from "my_button.slint";
import { ActionPanel } from "action_panel.slint";
import { HorizontalSpacer } from "spacers.slint";

export component MainPage inherits Rectangle {
    callback get(string);
    callback delete(string);
    callback post();
    callback logout();
    callback create-dir();

    callback update-metadata(int);

    in property <[File]> files: [];
    in property <[DirEntry]> subdirs: [];
    in property <string> current-path: "/";

    callback navigate-to-dir(string);
    callback navigate-back();

    background: rgba(195, 213, 235, 1);

    VerticalLayout {
        padding: 8px;
        spacing: 16px;

        HorizontalLayout {
            vertical-stretch: 1;
            spacing: 16px;
            padding: 16px;

            FileExplorer {
                vertical-stretch: 1;
                drop-shadow-blur: 30px;
                drop-shadow-color: rgba(0, 0, 0, 0.35);

                files: files;
                subdirs: subdirs;
                current-path: current-path;

                navigate-to-dir(path) => {
                    navigate-to-dir(path);
                }

                navigate-back => {
                    navigate-back();
                }

                update-metadata(name, path, size) => {
                    metadata-section.file-name = name;
                    metadata-section.path = path;
                    metadata-section.size = size;
                }
            }

            metadata-section := FileMetadataSection {
                vertical-stretch: 1;
                drop-shadow-blur: 30px;
                drop-shadow-color: rgba(0, 0, 0, 0.35);

                get(path) => {
                    get(path);
                }

                delete(path) => {
                    delete(path);
                    self.file-name = "-";
                    self.path = "-";
                    self.size = "-";
                }
            }
        }

        HorizontalLayout {
            min-height: 80px;

            HorizontalSpacer {
                horizontal-stretch: 1;
            }

            ActionPanel {
                horizontal-stretch: 0.1;
                drop-shadow-blur: 30px;
                drop-shadow-color: rgba(0, 0, 0, 0.35);

                post => {
                    post();
                }

                create-dir => {
                    create-dir();
                }

                logout => {
                    logout();
                }
            }

            HorizontalSpacer {
                horizontal-stretch: 1;
            }
        }
    }
}
