import { Button } from "std-widgets.slint";
export component MyButton inherits TouchArea {
    in property <string> text: "";

    in property <color> static-bg: rgba(255, 255, 255, 0.7);
    in property <color> hover-bg: rgba(255, 255, 255, 0.9);

    in property <bool> bold: false;

    in property <int> fontsize: 16;
    in property <color> font-color: black;

    mouse-cursor: pointer;
    Rectangle {
        background: root.has-hover ? hover-bg : static-bg;
        border-width: 1px;
        border-color: rgba(255, 255, 255, 0.2);
        border-radius: 16px;
        drop-shadow-blur: 30px;
        drop-shadow-color: rgba(0, 0, 0, 0.15);

        animate background {
            duration: 150ms;
            easing: ease-in;
        }

        HorizontalLayout {
            padding-top: 8px;
            padding-bottom: 8px;

            Text {
                text: text;
                font-size: fontsize * 1px;
                vertical-alignment: center;
                horizontal-alignment: center;

                font-weight: bold ? 600 : 400;

                color: font-color;

                wrap: word-wrap;
            }
        }
    }
}
