import { MyButton } from "my_button.slint";
import { VerticalSpacer } from "spacers.slint";
import { ScrollView } from "std-widgets.slint";
import { File } from "file_explorer.slint";

export component FileMetadataSection inherits Rectangle {
    in-out property <string> file-name: "-";
    in-out property <string> path: "-";
    in-out property <string> size: "-";

    background: white;
    border-radius: 16px;
    max-width: 420px;

    callback get(string);
    callback delete(string);

    ScrollView {

        if (file-name == "-" && path == "-" && size == "-"): VerticalLayout {
            alignment: center;
            spacing: 10px;

            Text {
                text: "Click a file for more info";
                font-size: 18px;
                font-weight: 500;
                color: rgba(0,0,0,0.4);
                horizontal-alignment: center;
            }
        }

        if(file-name != "-" || path != "-" || size != "-"):VerticalLayout {
            alignment: start;
            padding: 40px;
            spacing: 24px;

            HorizontalLayout {
                alignment: center;
                Rectangle {
                    height: 180px;
                    width: 180px;
                    background: white;
                    border-width: 2px;
                    border-color: black;
                }
            }

            Text {
                text: file-name;
                font-size: 28px;
                font-weight: 600;
                horizontal-alignment: center;
                color: black;
            }

            VerticalLayout {
                spacing: 4px;
                Text {
                    text: "Path";
                    font-size: 18px;
                    horizontal-alignment: center;
                    color: rgba(0,0,0,0.25);
                }

                Text {
                    text: path;
                    font-size: 18px;
                    font-weight: 400;
                    horizontal-alignment: center;
                    color: rgba(0,0,0,0.6);
                }
            }

            VerticalLayout {
                spacing: 4px;
                Text {
                    text: "Size";
                    font-size: 18px;
                    horizontal-alignment: center;
                    color: rgba(0,0,0,0.25);
                }

                Text {
                    text: size;
                    font-size: 18px;
                    font-weight: 400;
                    horizontal-alignment: center;
                    color: rgba(0,0,0,0.6);
                }
            }

            MyButton {
                text: "Download File";
                static-bg: rgba(79, 232, 171, 0.25);
                hover-bg: rgba(79, 232, 171, 0.5);
                fontsize: 20;

                clicked => {
                    get(path);
                }
            }

            MyButton {
                text: "Delete File";
                static-bg: rgba(232, 79, 79, 0.25);
                hover-bg: rgba(232, 79, 79, 0.5);
                fontsize: 20;

                clicked => {
                    delete(path);
                }
            }
        }
    }
}
