import { FileCard } from "file_card.slint";
import { ScrollView } from "std-widgets.slint";
import { MyButton } from "my_button.slint";

export struct File {
    name: string,
    path: string,
    size: string,
}

export component FileExplorer inherits Rectangle {
    in property <[File]> files: [];

    callback update-metadata(string, string, string);

    property <int> gap: 12;

    border-radius: 16px;
    background: white;

    ScrollView {

        VerticalLayout {
            padding: 32px;

            spacing: gap * 1px;

            if (files.length == 0): Text {
                text: "No files :^)";
                font-size: 24px;
                font-weight: 600;
                color: rgba(0,0,0,0.5);
                horizontal-alignment: center;
                vertical-alignment: center;
            }

            for file[i] in files: VerticalLayout {
                FileCard {
                    name: file.name;
                    path: file.path;
                    size: file.size;
                    date: "dd/mm/yyyy";

                    clicked => {
                        update-metadata(self.name, self.path, self.size);
                    }
                }

                spacing: gap * 1px;

                if (i < root.files.length - 1): Rectangle {
                    height: 1px;
                    background: #d0d0d0;
                    width: 95%;
                }
            }
        }
    }
}
