import { MyButton } from "my_button.slint";
import {
    Button,
    LineEdit,
    HorizontalBox,
    VerticalBox,
} from "std-widgets.slint";
import { FileExplorer } from "file_explorer.slint";
import { FileMetadataSection } from "file_metadata_section.slint";

export component MainPage inherits Rectangle {
    callback get(string);
    callback post();
    callback logout();

    in-out property <[string]> files: [];

    //    background: rgba(76, 84, 94, 1);
        background: rgba(195, 213, 235, 1);

    VerticalLayout {
        padding: 8px;
        alignment: center;
        HorizontalLayout {
            spacing: 16px;
            padding: 16px;

            FileExplorer {
                vertical-stretch: 1;
                drop-shadow-blur: 30px;
                drop-shadow-color: rgba(0, 0, 0, 0.35);
            }

            FileMetadataSection {
                vertical-stretch: 1;
                drop-shadow-blur: 30px;
                drop-shadow-color: rgba(0, 0, 0, 0.35);
            }
        }
    }
}
