import {
    Button,
    LineEdit,
    HorizontalBox,
    VerticalBox,
} from "std-widgets.slint";
import { MyButton } from "my_button.slint";
import { LoginScreen } from "login_screen.slint";
import { MainPage } from "main_page.slint";
import { FileExplorer, File } from "file_explorer.slint";


export component MainWindow inherits Window {
    title: "Personal Cloud";

    min-width: 1000px;
    min-height: 800px;

    preferred-width: 1400px;
    preferred-height: 800px;

    in property <[File]> files: [];

    callback try-login(string, string);

    callback get(string);
    callback post();
    callback logout();
    callback delete(string);

    callback update-files();

    in-out property <bool> is-logged: false;

    background: white;

    if !is-logged: LoginScreen {
        try-login(name, passwd) => {
            root.try-login(name, passwd);
        }
    }

    if is-logged: MainPage {
        files: root.files;
        get(file-path) => {
            root.get(file-path);
        }
        post() => {
            root.post();
        }
        logout => {
            root.logout();
        }
        update-files => {
            root.update-files();
        }
        delete(path) => {
            delete(path);
        }
    }
}
