import {
    Button,
    LineEdit,
    HorizontalBox,
    VerticalBox,
} from "std-widgets.slint";
import { MyButton } from "my_button.slint";
import { LoginScreen } from "login_screen.slint";
import { MainPage } from "main_page.slint";

export component MainWindow inherits Window {
    title: "Personal Cloud";

    min-width: 1000px;
    min-height: 800px;

    preferred-width: 1400px;
    preferred-height: 800px;

    callback try-login(string, string);

    callback get(string);
    callback post();
    callback logout();

    in-out property <bool> is-logged: true;

    if !is-logged: LoginScreen {
        try-login(name, passwd) => {
            root.try-login(name, passwd);
        }
    }

    if is-logged: MainPage {
        get(file-path) => {
            root.get(file-path);
        }
        post() => {
            root.post();
        }
        logout => {
            root.logout();
        }
    }
}
