import { MyButton } from "my_button.slint";
import {
    Button,
    LineEdit,
    HorizontalBox,
    VerticalBox,
} from "std-widgets.slint";
import { FileExplorer, File } from "file_explorer.slint";
import { FileMetadataSection } from "file_metadata_section.slint";
import { ActionPanel } from "action_panel.slint";

export component MainPage inherits Rectangle {
    callback get(string);
    callback delete(string);
    callback post();
    callback logout();
    callback show-history();

    callback update-files();

    in property <[File]> files: [];

    background: rgba(195, 213, 235, 1);

    VerticalLayout {
        padding: 8px;
        spacing: 16px;

        HorizontalLayout {
            vertical-stretch: 1;
            max-height: parent.height - 120px;
            spacing: 16px;
            padding: 16px;

            FileExplorer {
                vertical-stretch: 1;
                drop-shadow-blur: 30px;
                drop-shadow-color: rgba(0, 0, 0, 0.35);

                files: files;
            }

            FileMetadataSection {
                vertical-stretch: 1;
                drop-shadow-blur: 30px;
                drop-shadow-color: rgba(0, 0, 0, 0.35);

                get(path) => {
                    get(path);
                }

                delete(path) => {
                    delete(path);
                }
            }
        }

        HorizontalLayout {
            alignment: center;
            min-height: 80px;

            ActionPanel {
                drop-shadow-blur: 30px;
                drop-shadow-color: rgba(0, 0, 0, 0.35);

                logout => {
                    logout();
                }

                post => {
                    post();
                }

                show-history => {
                    show-history();
                }
            }
        }
    }
}
